import _Inventory from './home/Inventory';
import _QuickRegist from './registered-vehicle/QuickRegist';
import _DailyPnl from './home/DailyPnl';
import _DailyCost from './home/DailyCost';
import _Aggregation from './data-aggregation/Aggregation';
import _DailyStatistics from './data-aggregation/DailyStatistics';
import _RegisteredManagement from './registered-vehicle/RegisteredManagement';
import _SalesCompletionHistory from './sales-completion/SalesCompletionHistory';
import _DetailVehicleManagement from './detail-vehicle/DetailVehicleManagement';
import _RatioDonut from './data-aggregation/RatioDonut';

export const Inventory = _Inventory;
export const DailyPnl = _DailyPnl;
export const DailyCost = _DailyCost;
export const Aggregation = _Aggregation;
export const DailyStatistics = _DailyStatistics;
export const QuickRegist = _QuickRegist;
export const RegisteredManagement = _RegisteredManagement;
export const SalesCompletionHistory = _SalesCompletionHistory;
export const RatioDonut = _RatioDonut;
export const DetailVehicleManagement = _DetailVehicleManagement;
