apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: NAMESPACE_NAME
  name: PROJECT_NAME
spec:
  selector:
    matchLabels:
      app: PROJECT_NAME
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: PROJECT_NAME
    spec:
      containers:
        - name: PROJECT_NAME
          image: gcr.io/handle-304204/PROJECT_NAME:TAG_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: PROJECT_PORT
          envFrom:
            - configMapRef:
                name: carmerce-partner-front-config
